### ISSUE TITLE
Handle Garmin GPX Conversion

### ISSUE THREAD

**Issue by cbeddow** [mapillary/mapillary_tools#416]
User reports:  “ERROR: mapillary_tools process not possible when parameter = --geotag_source gpx”.

User finds the issue is that the specific Garmin device's GPX seems to not match the format that mapillary_tools expects:

* --geotag_source gpx is processing a gpx file.

* But mapillary_tools is expecting a Unix, UTF8 file.

* If the gpx file is created by Garmin GPS and processed on a Windows OS, the file is not expected format.

* mapillary_tools is not validating the input file and not returning an Error Message I understand.

To convert the GPX file:

* Replace CrLf (Windows) by Lf (Unix)

* Remove 3x BOM header characters (Windows)

* And - perhaps - convert to UTF8.

Now the GPX input file will be processed correctly

^^ following this, we should consider either a handler with the GPX process fails to then run this conversion, or a handler before attempting to process the GPX to run this conversion or see if the headers exist and should be removed, and if not in UTF8 to then convert it.

@ptpt could you take a look at this in a next update?

**Comment by cbeddow** [comment]
Additional notes:

* Both files are UTF-8, so that’s NOT the issue.

* Windows (CR LF) or Unix (LF)

File NOT OK = Windows (CR LF)

File NOT OK = Unix (LF)

I don’t know – at this moment – if (CR LF) or (LF) is relevant.

But for Unix (LF) seems best option, always accepted.

* But ALSO: Garmin GPX is Windows (CR LF), UTF-8-BOM

BOM might be the only issue!

BOM is first 3 – invisible - Characters in a file: Chr(239) & Chr(187) & Chr(191)

These 3 characters have to be removed!

This is the Error Message: “ERROR:root:not well-formed (invalid token): line 1, column 1”

IMO: line 1, column 1 (+2, +3) = BOM

Remark:

* Unix don’t need BOM to tell Unix this is UTF-8

* Sometimes Unix don’t like BOM (Professionally I have seen a Unix Webshop that refuses my Interface file because of BOM)

* BOM is Windows, to inform Windows this is UTF-8. (Ehhh, stupid Windows)

**Comment by pbb72** [comment]
Just to add a small nuance: BOM (Byte Order Mark) is *not* a requirement for Windows. In Windows, interpreting the correct file encoding is up to the software, not the OS. However, you were almost correct, almost all Microsoft software and compilers require and use the BOM for UTF-8 files. So while it's not a requirement for Windows software, it is the de facto default...

Also not that while the Unicode Standard does not recommend using a BOM for UTF-8, it does allow it, so it is perfectly valid.

**Comment by ptpt** [comment]
@AnkEric could you check if it's fixed in https://github.com/mapillary/mapillary_tools/pull/446 (which upgrade the gpx library to latest) while you are extensively testing mapillary_tools ;)

**Comment by AnkEric** [comment]
> @AnkEric could you check if it's fixed in #446 (which upgrade the gpx library to latest) while you are extensively testing mapillary_tools ;)

I could if I would know how to get this: "which upgrade the gpx library to latest"".

It's not in my recent update:

python3 -m pip install --force-reinstall --upgrade git+https://github.com/mapillary/mapillary_tools

(Or: it's not fixed...)

**Comment by ptpt** [comment]
Could you list all installed liaraies

```
python3 -m pip show gpxpy
Name: gpxpy
Version: 1.4.2
Summary: GPX file parser and GPS track manipulation library
Home-page: https://github.com/tkrajina/gpxpy
Author: Tomo Krajina
...
```

It should be 1.4.2. If not

```
python3 -m pip install -U gpxpy
```
